# Generated by Django 5.2.5 on 2025-08-30 13:06

import blueprints.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=blueprints.models.plot_upload_path,
                    ),
                ),
                ("bedroom1_size", models.CharField(blank=True, max_length=50)),
                ("bedroom2_size", models.CharField(blank=True, max_length=50)),
                ("bedroom3_size", models.CharField(blank=True, max_length=50)),
                ("bedroom4_size", models.CharField(blank=True, max_length=50)),
                ("bedroom5_size", models.CharField(blank=True, max_length=50)),
                ("bathroom1_size", models.CharField(blank=True, max_length=50)),
                ("bathroom2_size", models.CharField(blank=True, max_length=50)),
                ("bathroom3_size", models.CharField(blank=True, max_length=50)),
                ("bathroom4_size", models.CharField(blank=True, max_length=50)),
                ("bathroom5_size", models.CharField(blank=True, max_length=50)),
                ("living_size", models.CharField(blank=True, max_length=50)),
                ("dining_size", models.CharField(blank=True, max_length=50)),
                ("kitchen_size", models.CharField(blank=True, max_length=50)),
                ("parking_size", models.CharField(blank=True, max_length=50)),
                ("porch_size", models.CharField(blank=True, max_length=50)),
                ("utility_size", models.CharField(blank=True, max_length=50)),
                ("store_size", models.CharField(blank=True, max_length=50)),
                ("additional_rooms", models.CharField(blank=True, max_length=255)),
                ("layout_style", models.CharField(blank=True, max_length=100)),
                (
                    "total_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_blueprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_blueprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
