# Generated by Django 5.2.5 on 2025-08-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueprints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotblueprint",
            name="plot_height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="plotblueprint",
            name="plot_unit",
            field=models.CharField(
                blank=True,
                choices=[("ft", "Feet"), ("m", "Meter")],
                default="ft",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="plotblueprint",
            name="plot_width",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
