# Generated by Django 5.2.5 on 2025-09-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blueprints",
            "0002_plotblueprint_plot_height_plotblueprint_plot_unit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plotblueprint",
            name="drawing_room_size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="plotblueprint",
            name="hall_size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="plotblueprint",
            name="ots_size",
            field=models.CharField(blank=True, max_length=50, verbose_name="O.T.S"),
        ),
        migrations.AddField(
            model_name="plotblueprint",
            name="wash_area_size",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
